export const PREFIX = "@auth/";

export const ASYNC_TODO_INIT = `${PREFIX}ASYNC_TODO_INIT`;

export const FILTER_TODO_SUCCESS = `${PREFIX}FILTER_TODO_SUCCESS`;

export const GET_ALL_COMPLETEDCOUNT_SUCCESS = `${PREFIX}DELETE_TODOSTATUS_SUCCESS`;